### ISSUE TITLE
Admin issues with Firefox

### ISSUE THREAD

**Issue by tomplex** [qrush/skyway#56]
When I hover over the "admin" tab, the menu opens up on the other side of the screen, like so:

![screenshot](https://cloud.githubusercontent.com/assets/8109856/5791295/be4eb1aa-9e99-11e4-87f2-dc4ac559de00.png)

This renders all admin options inaccessible on this browser.

**Comment by darrenkemp** [comment]
This happens to me too. Right click on the dropdown so the menu pops up
then you can go click what you need too.

Dk

**Comment by qrush** [comment]
Agh. Yeah I haven't tested it in Firefox, just Chrome and Safari. Please
use those for the time being :grin:

**Comment by qrush** [comment]
Actually that's happening in Chrome too now, wtf. Will investigate.

**Comment by darrenkemp** [comment]
Happens in Chrome too.

Also, admin seems broken:

[image: Inline image 1]

On Sun, Jan 18, 2015 at 9:25 AM, Nick Quaranto <notifications@github.com>
wrote:

> Agh. Yeah I haven't tested it in Firefox, just Chrome and Safari. Please
> use those for the time being :grin:
>
> On Sat, Jan 17, 2015 at 10:44 PM, darrenkemp <notifications@github.com>
> wrote:
>
> > This happens to me too. Right click on the dropdown so the menu pops up
> > then you can go click what you need too.
> >
> > Dk
> > On Jan 17, 2015 10:41 PM, "tomplex" <notifications@github.com> wrote:
> >
> > > When I hover over the "admin" tab, the menu opens up on the other side
> > of
> > > the screen, like so:
> > >
> > > [image: screenshot]
> > > <
> >
> https://cloud.githubusercontent.com/assets/8109856/5791295/be4eb1aa-9e99-11e4-87f2-dc4ac559de00.png>
>
> >
> > >
> > > This renders all admin options inaccessible on this browser.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/qrush/skyway/issues/56>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/qrush/skyway/issues/56#issuecomment-70395372>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qrush/skyway/issues/56#issuecomment-70410062>.
>



-- 
Darren Kemp
darrenkemp@gmail.com

**Comment by qrush** [comment]
That didn't work. It's happier in Chrome for me since I deployed yesterday. Can you try uploading that again?
