### ISSUE TITLE
Missing shows

### ISSUE THREAD

**Issue by darrenkemp** [qrush/skyway#57]
11/25 and 11/27 don't seem to pull show pages but they are listed on the overall tour.

**Comment by qrush** [comment]
Fixed. They were created while i was thrashing about and left the timezone on eastern, and couldn't be found now that it's back on UTC.

**Comment by darrenkemp** [comment]
Thanks brother, I figured it was something like that.

-DK


On Thu, Nov 5, 2015 at 4:38 PM, Nick Quaranto <notifications@github.com>
wrote:

> Fixed. They were created while i was thrashing about and left the timezone
> on eastern, and couldn't be found now that it's back on UTC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qrush/skyway/issues/57#issuecomment-154200937>.
>



-- 
Darren Kemp
darrenkemp@gmail.com
